### ISSUE TITLE
Model simulation issue

### ISSUE THREAD

**Issue by zlqs1985** [floswald/MOpt.jl#10]
Hi, Florian. One silly stupid question. To apply this code, do I need to simulate my model under every parameter combination (to obtain the empirical moments, I need dozens of simulations runs with 1000 simulated individuals each run), or alternatively,  just one simulation at the initial time? As you know, each round of simulation take a lot of time, it's a crucial matter.

**Comment by floswald** [comment]
the library will take care of choosing the parameters at which to evaluate your objective function, that's the whole point. if your objective function involves simulating some data, given the parameter, than you have to do one simulation per evaluation, yes.
