### ISSUE TITLE
Hope some econ examples can be provided

### ISSUE THREAD

**Issue by zlqs1985** [floswald/MOpt.jl#8]
Hi, Florian:
     This is a really cool stuff to make SMM estimation fesible to econ phD like me.
     However, after reading the document, I still cannot easily map the code to the steps described in your paper.  In your JMP and “Consumer Bankruptcy and Mortgage Default”, a parameter are estimated by matching one certain simulated moment to real moments from data, or even via multiple moments,which part of code correspond to this step? (I believe it's in the objective function). The arguments for `addMoment` are just two DataArrays, I don't quite understand what they represent.
    Moreover, you also add some auxiliary models in these papers, can we now implement this in MOpt.jl?
    Anyway, you guys did a great job.

**Comment by floswald** [comment]
I can't see any question about the code here so I close this issue.
